# Generated by Django 5.2.8 on 2025-12-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_user_id_830b32_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_mode',
            field=models.CharField(choices=[('global', 'Global'), ('book', 'Book')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.chapter'),
        ),
    ]
