# Generated by Django 5.2.8 on 2026-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interviewsession_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
