# Generated by Django 5.2.8 on 2026-02-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='College admin email', max_length=254, null=True),
        ),
    ]
