# Generated by Django 5.2.8 on 2026-01-05 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weeklyquiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='topicstat',
            name='core_topics_user_id_5b6d1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicstat',
            name='core_topics_topic_64e4e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='userchapterprogress',
            name='core_userch_user_id_cfb779_idx',
        ),
        migrations.RemoveIndex(
            model_name='userchapterprogress',
            name='core_userch_chapter_376e64_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_push',
        ),
        migrations.AddField(
            model_name='dailyquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquizattempt',
            unique_together={('user', 'date')},
        ),
    ]
