# Generated by Django 5.2.8 on 2026-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_institution_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='student_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
