# Generated by Django 5.2.8 on 2026-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyquizattempt_dailyquizquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='ai_tip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
