# Generated by Django 5.2.8 on 2026-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quizattempt_ai_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
