# Generated by Django 5.2.8 on 2026-02-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_institution_student_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='invite_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
