# Generated by Django 5.2.8 on 2026-01-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quizattempt_ai_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='ai_explanation',
        ),
    ]
